# Generated by Django 4.1.3 on 2022-12-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_company_contract_author_contractor_author_and_more'),
        ('users', '0003_remove_profile_employee_number_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layout.company'),
        ),
    ]
