# Generated by Django 4.1.1 on 2022-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_number',
            field=models.CharField(default='111', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='index_number',
            field=models.CharField(default='111', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='number_in_contract',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.CharField(default='111', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
