# Generated by Django 4.1.1 on 2022-09-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('layout', '0002_remove_order_contractor_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='user_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
