# Generated by Django 4.1.1 on 2022-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_contract_user_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ending',
            field=models.BooleanField(default=False),
        ),
    ]
