# Generated by Django 4.1.4 on 2022-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_remove_storage_author_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Is Ordered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Is ordered'),
        ),
    ]
