# Generated by Django 4.1.4 on 2023-01-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_contract_email_sent_alter_order_is_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producent',
            new_name='producer',
        ),
    ]
